version: '3'
services:
  postgres-identity:
    container_name: identity-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: identity-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/identity:/data/postgres
  postgres-developer:
    container_name: dev-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: dev-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/dev:/data/postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - skill-spectrum
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - skill-spectrum
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  redis:
    image: redis
    ports:
      - "6379:6379"
networks:
  skill-spectrum:
    driver: bridge