spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: invitation-code-service
server:
  port: 1465
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

#  http://localhost:6379/swagger-ui/index.html
