spring:
  application:
    name: reviewer-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qaisar
    password: qaisar
    url: jdbc:postgresql://localhost:5438/reviewer-service
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    queues:
      reviewer: reviewer-saving-queue
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring:
        json:
          trusted:
          packages: "*"
      bootstrap-servers: http://localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8012