spring:
  application:
    name: task-service
  datasource:
    url:  jdbc:postgresql://localhost:5435/task-service
    password: qaisar
    username: qaisar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8088
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html