spring:
  application:
    name: grading-service
  datasource:
    url:
    password: qaisar
    username: qaisar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create