spring:
  application:
    name: developer-service
  datasource:
    url:  jdbc:postgresql://localhost:5434/dev-service
    password: qaisar
    username: qaisar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8078
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka