spring:
  application:
    name: developer-service
  datasource:
    url:  jdbc:postgresql://localhost:5434/dev-service
    password: qaisar
    username: qaisar
    driver-class-name: org.postgresql.Driver